### PR TITLE
Adds SchedulingPolicy to Gateway api type

### PR DESCRIPTION
**Pull request by danehans**
Previously, a user had no ability to constrain the placement of a gateway to a specific node or a set of nodes. `SchedulingPolicy` provides a schematic approach for scheduling a gateway using a [nodeSelector](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector) or [tolerations](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/).

/assign @bowei

### CODE REVIEW

**Comment by danehans** [comment]
Should `SchedulingPolicy` also support [node affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity)?

**Comment by danehans** [comment]
fixes issue: https://github.com/kubernetes-sigs/service-apis/issues/54

**Comment by hbagdi** [comment]
1. Should this not be done via NodeSelectors on the Deployment/Pod for each instance of the proxy?
2. Even if we do do this, why should this not be a concern of GatewayClass instead?

**Comment by danehans** [comment]
> Should this not be done via NodeSelectors on the Deployment/Pod for each instance of the proxy?

@hbagdi this PR supports `NodeSelector` as a type of `SchedulingPolicy`. Adding `SchedulingPolicy` support will allow users to fine-tune the Gateway deployment using service-apis instead of performing the task manually.

> Even if we do do this, why should this not be a concern of GatewayClass instead?

Let's say I have a `GatewayClass` named "private". This GatewayClass is used for intra-cluster communications and is associated to multiple gateways. A subset of the gateways should be scheduled to worker nodes with increased capacity used for storage replication. I create a `Gateway` configured with `SchedulingPolicy`, directing the deployment to the high capacity nodes and associate it to `GatewayClass` "private".

**Comment by bowei** [comment]
I have a couple of question about this:

1. How portable do we expect this to be? 
1. Why is does this need to be a the Gateway API? vs GatewayClass.

GatewayClass describes infrastructure.
Gateway is more about a request from the user of the infrastructure.

This seems more like part of the internal implementation of the controller.

**Comment by danehans** [comment]
@bowei commit `238e532` moves the scheduling policy to `GatewayClass`.

> How portable do we expect this to be?

I expect a gateway class controller to run as a pod. The underlying mechanisms of a scheduling policy, i.e. [node selector](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector), have been around for a long time. Therefore, I would expect most clusters to support this feature. I did mark the `SchedulingPolicy` field as `Extended`.

**Comment by bowei** [comment]
Cloud controllers don't typically run in cluster.
Also, controllers for external LBs (e.g. F5) don't correspond to the a physical deployments.
I know of several large deployments of nginx controller that run off cluster as well on a dedicated pool of VMs.

This might be one of those things that is very use-case specific.

**Comment by jpeach** [comment]
Discussed in office hours. For in-cluster ingress, the gateway class is backed by some kind of proxy deployment, but what kind of proxy deployment and how it is scheduled can be described in the ParametersRef using vendor specific config. So we could leave this for now and look at standardizing what vendors do?

**Comment by danehans** [comment]
Closing based on the consensus that `Gateway` scheduling is implementation specific.

cc: @ironcladlou @Miciah

**Pull request closed without merging**
