### PR TITLE
remove unnecessary deps

### PR DESCRIPTION
**Pull request by hbagdi**

### CODE REVIEW

**Comment by jpeach** [comment]
Why are these unnecessary?

**Comment by hbagdi** [comment]
> Why are these unnecessary?

More of an experiment. I _think_ we don't need to track them in `go.mod`. I blew `go.mod` away and then re-init it, and this is what it came to. And things continue to work as expected as well.

**Comment by jpeach** [comment]
> > Why are these unnecessary?
> 
> More of an experiment. I _think_ we don't need to track them in `go.mod`. I blew `go.mod` away and then re-init it, and this is what it came to. And things continue to work as expected as well.

Probably because you removed tools.go as well. This is needed to force venturing for things that exec with `go run`.

**Comment by jpeach** [comment]
xref #352

**Comment by hbagdi** [comment]
This doesn't work as James pointed out.

**Pull request closed without merging**
