### PR TITLE
Update controller-runtime dep

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by howardjohn** [comment]
We might just want to wait for 1.18 to ship and then update to that as well

**Comment by bowei** [comment]
hey can you add more detail to the PR description (why updating etc)

**Comment by howardjohn** [comment]
I had originally thought this was going to block us from updating to k8s 1.18 client-go due to some changes there, but it seems to work actually. so no strong motivation any longer other than staying on the latest and greatest

**Pull request closed without merging**
