### PR TITLE
Document root CRD objects as API resource types.

### PR DESCRIPTION
**Pull request by jpeach**
When finding the set of root CRD types, the documentation
generator checks for the `+genclient` annotation, ratherd
than the newer `+kubebuilder:object:root`.

Adding `+genclient` makes the root CRD type objects appear in the
resource list at the head of the API documentation, which improves
their visibility.

Signed-off-by: James Peach <jpeach@vmware.com>

### CODE REVIEW

**Comment by jpeach** [comment]
xref https://github.com/ahmetb/gen-crd-api-reference-docs/issues/15

**Comment by jpeach** [comment]
@robscott Can you PTAL at your leisure?

**Comment by robscott** [comment]
Thanks! This is a nice addition. For anyone curious, in addition to moving all the top level resources to the top, it adds some helpful top-level links to them.

Screen Shot 2020-06-03 at 10 40 50 PM

/ok-to-test
/lgtm

**Pull request merged**
