### PR TITLE
Adds release cadence to dev docs

### PR DESCRIPTION
**Pull request by danehans**
Adds release cadence to dev guide.

/assign @bowei

### CODE REVIEW

**Comment by danehans** [comment]
@bowei while working my way through the [dev guide](https://kubernetes-sigs.github.io/service-apis/devguide/), I ran `make -f docs.mk` and this release cadence content was generated. Maybe you did not generate the docs from a previous commit?

**Comment by danehans** [comment]
Note that [mkdocs](https://www.mkdocs.org/) is adding unnecessary whitespace to `docs/devguide/index.html` and I had to manually remove after running `make -f docs.mk`.

**Comment by bowei** [comment]
I think there was a commit that was merged from previous that didn't autogen the docs.
https://github.com/kubernetes-sigs/service-apis/issues/19

**Comment by danehans** [comment]
@bowei that's what I figured. Can this get a `/lgtm` until a PR is merged to fix https://github.com/kubernetes-sigs/service-apis/issues/19?

**Comment by danehans** [comment]
@bowei PR #23 fixes #19. I did not include the release cadence docs generation in PR #23, so this PR is still needed.

**Comment by danehans** [comment]
@bowei I removed the code to fix issue #19 from https://github.com/kubernetes-sigs/service-apis/pull/23 in favor of https://github.com/kubernetes-sigs/service-apis/pull/24 from @youngnick

**Comment by bowei** [comment]
There seem to be conflicts in this PR, you might want to rebase.

**Comment by danehans** [comment]
The release cadence docs update was added by commit `e56eeaf76ec892b9c1ff028c1055c529463e23fc`.

Closing this PR.

**Pull request closed without merging**
