### PR TITLE
Create autogenerate client/lister/informers

### LINKED ISSUE #61: Generated Informers for non controller-runtime use
Already-written controllers that do not use controller-runtime and kubebuilder will find it difficult to consume these APIs without having generated Informers.

This issue proposes that we add automated generation of the required code to use the new APIs with Informers (so, a clientset, listers, and informers). I'll prepare a PR with the change as well for review.

This will make the implementation of these types in an experimental fashion in Contour and any other controller that is still using Informers much easier.

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes #61

The goal here is to autogenerate some of the typed clients, so implementators can easily access the types. This is split in 3 commits, one adding the groundwork, the 2nd moves api -> apis,  and the third actually running the gen.

This unfortunately involved changing the folder from `api` to `apis` because k8s client gen expects the folders to be in a certain shape (I think `api` is a special case for the core types basically). We might be able to avoid it with some more custom generator code, but I figured it would be simpler to change the folder, as there are not too many implementators yet and its fairly easy to update with a quick `sed`. https://github.com/kubernetes/code-generator/blob/121d9d35590dece219d7098e9b6603496337ce77/cmd/client-gen/types/types.go#L40 is the root cause of this, I spent a long time trying to work around it without success. There is no strong reason we `api` is better than `apis` as far as I know, so hopefully this isn't too bad

I have tested this locally in Istio's implementation so I think we got everything in the right place.

### CODE REVIEW

**Comment by bowei** [comment]
/ok-to-test

(https://kubernetes.slack.com/archives/CR0H13KGA/p1591927519213000)

**Comment by howardjohn** [comment]
Actually I am going to see if we can do it without moving stuff

**Comment by howardjohn** [comment]
https://github.com/kubernetes/code-generator/blob/121d9d35590dece219d7098e9b6603496337ce77/cmd/client-gen/types/types.go#L40 may require us to move from api -> apis

**Comment by akutz** [comment]
Hi,

May I ask the reason for the generated client sets? I was under the impression that most projects are moving away from that and favoring the controller-runtime client? This change introduces a number of additional dependencies that will affect downstream consumers of this library.

Also, the `api` directory rename is not a small thing. I wonder if these changes are moving counter to the direction other Kubernetes projects are moving?

**Comment by howardjohn** [comment]
@akutz I am a bit confused by the "additional dependencies" that you mentioned. The change here has no change to go.mod/go.sum which I interpret as no changes to dependencies? Is that not accurate?

**Comment by akutz** [comment]
Doh! You're absolutely correct! Mea culpa. I am just used to the clientgen tools pulling in so much stuff. I should have looked more closely.

**Pull request merged**
