### PR TITLE
Update Listener.Port *int32 to Listener.Ports []int32

### PR DESCRIPTION
**Pull request by akutz**
This PR includes two commits:

### Patch 1
Run `hack/update-proto.sh` as this resulted in a number of changes to the generated protobufs, even without any other code updates. I am not sure if this is due to my version of `protoc`, which I installed with `brew install protoc`. 

```shell
$ protoc --version
libprotoc 3.11.4
```

This update was placed into a discreet commit as otherwise the subsequent patch would have included it regardless.

### Patch 2
Update the field `Listener.Port *int32` to a list of ports, `Listener.Ports []int32`. This is the intent based on the existing documentation, as well as it makes sense that a listener should be able to listen on multiple ports.

cc @maplain @andrewsykim

### CODE REVIEW

**Comment by robscott** [comment]
Thanks for fixing this!

/lgtm

**Comment by robscott** [comment]
We talked about this today in our office hours meeting, and it turns out that it actually makes more sense for a single port to be tied to a Gateway listener. The protocol here is actually really referring to a l7 protocol (currently only HTTP and HTTPS) are supported, and it seems unlikely that you'd want to tie multiple ports to a single l7 protocol. So actually it looks like the field definition was correct and the corresponding comment was wrong. Does that approach make sense to you? If so, I can re-LGTM this if you change this PR to update the comment instead.

/lgtm cancel

**Comment by akutz** [comment]
Hmm. If this is meant for a single port, then it seems to me the entire model is in contradiction with itself. 

I think there is some confusion around what a Gateway is.  A Gateway is documented to represent an LB. 

Using ELB as an example, an LB has multiple listeners, each with a distinct port. 

But using other model, an LB had virtual servers, which a listener could also be.

The documentation indicates support for L4. I even opened (and closed, because I was sensing this contradiction) around TcpRoutes. 

The problem is that either an LB is an LB and has support for virtual servers (perhaps a new type?) or an LB represents a virtual server and the listeners should not have both IP addresses *and* ports.

Either way, to claim the API is strictly L7 is totally contradictory to the existing docs around intent, and throws many wrenches in the works for us.

**Comment by danehans** [comment]
@robscott after discussing this issue during our weekly meeting, one use case for having a listener with multiple ports comes to mind:

As a Developer, I have a web app that I would like to expose using service-apis. The web app has a FQDN of "foo.example.com" and listens on 443 for TLS connections and 80 for HTTP connections. Currently, this requires 2 listeners. Each listener gets a separate IP address. I use these addresses for creating foo.example.com A records. When users hit http://foo.example.com it may resolve to the TLS listener instead of the HTTP listener. Vice versa for https://foo.example.com. Thoughts?

cc: @Miciah @jpeach @costinm

**Comment by danehans** [comment]
Instead of simply pluralizing port, I suggest we follow existing k8s port sematics, where a `Port` includes `Name`, `Protocol` and `Number` properties. [ContainerPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core),  [EndpointPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#endpointport-v1beta1-discovery-k8s-io) and Istio Gateway [Port](https://istio.io/docs/reference/config/networking/gateway/#Port) are good examples. @robscott and @bowei what are your thoughts?

**Comment by akutz** [comment]
> Instead of simply pluralizing port, I suggest we follow existing k8s port sematics, where a `Port` includes `Name`, `Protocol` and `Number` properties. [ContainerPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core), [EndpointPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#endpointport-v1beta1-discovery-k8s-io) and Istio Gateway [Port](https://istio.io/docs/reference/config/networking/gateway/#Port) are good examples. @robscott and @bowei what are your thoughts?

I agree, but I still would like it to be plural. This is what I suggested during the call:

```yaml
listeners:
- name: web-1.com
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
```

The default protocol for service ports is already TCP, so this makes a lot of sense. Honestly, I think the entire API should follow pretty closely with the way [the ELB primitives](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference) work for:

* LoadBalancer
* Listener
* TargetGroup

**Comment by jpeach** [comment]
> @robscott after discussing this issue during our weekly meeting, one use case for having a listener with multiple ports comes to mind:
> 
> As a Developer, I have a web app that I would like to expose using service-apis. The web app has a FQDN of "foo.example.com" and listens on 443 for TLS connections and 80 for HTTP connections. Currently, this requires 2 listeners. Each listener gets a separate IP address.

Is there a requirement to give each listener a separate address? The listener address is optional and IIUC may not be supported by all kinds of controllers. In this case, I think you would specify 2 listeners, each with a port, and no addresses.

**Comment by akutz** [comment]
> Is there a requirement to give each listener a separate address? The listener address is optional and IIUC may not be supported by all kinds of controllers. In this case, I think you would specify 2 listeners, each with a port, and no addresses.

Exactly James! But in this case there is nowhere else to assign the address. It would have to be on the Gateway.

It seems to me if you do not support multiple ports for the listener, then the Gateway is the VirtualHost, not the load balancer that supports multiple virtual hosts. I would update the docs to indicate that a Gateway is 1:1 with a virtual server/virtual host/front-end. It's more accurate for most people outside of Ingress.

**Comment by jpeach** [comment]
> Instead of simply pluralizing port, I suggest we follow existing k8s port sematics, where a `Port` includes `Name`, `Protocol` and `Number` properties. [ContainerPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core), [EndpointPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#endpointport-v1beta1-discovery-k8s-io) and Istio Gateway [Port](https://istio.io/docs/reference/config/networking/gateway/#Port) are good examples. @robscott and @bowei what are your thoughts?

This could be interesting, but maybe it's a bit early. The Protocol field in Listener isn't well specced, so it's not clear to me what it would mean in combination with TLS and different kinds of routes. I don't think that we want the Istio semantics here, and we probably want to support both TLS passthrough and TLS termination on the same port 443.

**Comment by jpeach** [comment]
> > Is there a requirement to give each listener a separate address? The listener address is optional and IIUC may not be supported by all kinds of controllers. In this case, I think you would specify 2 listeners, each with a port, and no addresses.
> 
> Exactly James! But in this case there is nowhere else to assign the address. It would have to be on the Gateway.

You don't have to assign an address. For some gateway classes (e.g. Contour), the address will be fixed and known in advance.

> It seems to me if you do not support multiple ports for the listener, then the Gateway is the VirtualHost, not the load balancer that supports multiple virtual hosts. I would update the docs to indicate that a Gateway is 1:1 with a virtual server/virtual host/front-end. It's more accurate for most people outside of Ingress.

Yep, gateway is closest in concept to a virtual host that can be configured on some arbitrary load balancing data plane. We should keep iterating to clarify the docs :)

**Comment by akutz** [comment]
Hmm. I just think y’all are too focused on L7 HTTP and specific ideas about what LBs are based on your experience on Ingress. I’d start broader and build up. You’re starting narrow and trying to retcon L4 and other LB approaches, and even if it works, it will be ugly. Solve L4, then layer on top. Same for the LB model. Start wide and get narrower with each layer.

**Comment by akutz** [comment]
Either way though James, thank you for the clarification. It really does help me figure things out since I can adjust things based on your interpretation of the LB model.

**Pull request closed without merging**
