### PR TITLE
Adding RouteNamespaces for Gateway and GatewayClass

### PR DESCRIPTION
**Pull request by robscott**
This adds a new RouteNamespaces field to Gateway and GatewayClass. This simplifies the logic around Route Namespace selection and ensures consistent fields are used for both Gateway and GatewayClass. This removes the possibility of a nil selector. Nil values are often difficult to distinguish from empty values, and in this case they would have had wildly different meanings. I believe this approach will be easier to understand and document.

/cc @lelenanam @youngnick @howardjohn

### CODE REVIEW

**Comment by robscott** [comment]
This PR has been updated to account for some great feedback from #199. This now encompasses the scope of both PRs and this should fix #199. 

@bowei @danehans @jpeach Thanks for the feedback! Please take another look whenever you get a chance.

**Comment by bowei** [comment]
@robscott -- rebase?

**Comment by robscott** [comment]
@bowei rebased and ready for hopefully final review.

**Comment by robscott** [comment]
@bowei This has been rebased again.

**Comment by bowei** [comment]
/lgtm
/approve

There was some discussion about use of labeling in general, but we can merge this as it is somewhat orthogonal to this improvement.

**Pull request merged**
