### PR TITLE
Refactor httproute type to virtualserver

### PR DESCRIPTION
**Pull request by danehans**
Builds off PR https://github.com/kubernetes-sigs/service-apis/pull/101 from @jpeach, fully implementing `VirtualServer` API type.

/assign @bowei 
/cc @Miciah @youngnick

### CODE REVIEW

**Comment by jpeach** [comment]
@danehans I haven't looked at this yet, but do you have any opinion yet on whether this is a productive direction to explore?

**Comment by danehans** [comment]
Will reopen if [virtual host](https://docs.google.com/presentation/d/1HmEhFi75rnI68gAzgVRQ2-_zcG68CbXgKZpPkSysvTw/edit?usp=sharing) model is accepted.

**Comment by akutz** [comment]
I like this!

**Pull request closed without merging**
