### PR TITLE
Fix broken doc link

### PR DESCRIPTION
**Pull request by beriberikix**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Looks like there was a big doc change and this link wasn't updated.

### CODE REVIEW

**Comment by beriberikix** [comment]
Thanks @jpeach for sharing how to generate docs with `make generate`! Also tested with `mkdocs serve`.

**Comment by robscott** [comment]
Thanks!

/ok-to-test

**Review by hbagdi — APPROVED** [review]
A quick grep reveals that there is no other `/concepts` link in our docs.
Thanks for these fixes, @beriberikix.

/lgtm

**Comment by beriberikix** [comment]
So while this worked when testing locally, something broke when deployed. Currently it points to:

`https://kubernetes-sigs.github.io/api-overview/#extension-points` 

when it should be:

`https://kubernetes-sigs.github.io/service-apis/api-overview/#extension-points`. 

I can't see any obvious issues - any ideas?

**Comment by hbagdi** [comment]
@beriberikix I think this should fix it: https://github.com/kubernetes-sigs/service-apis/pull/497/files

**Pull request merged**
