### PR TITLE
Update go dependencies to v1.17.0 and go to 1.13.5

### LINKED ISSUE #2: Add basic hack/ verification scripts
Implement basic verification scripts (this will not be inclusive of all that will eventually be needed).

### Verify apache license

Go through all source code types (Makefile, go code, markdown) have the right apache license header.
We should be able to use existing scripts and adapt it to this repo. Although it may make sense to carve
these things out into a separate repo across the Kubernetes project.

### Verify document generation

Run the `make docs` command to generates docs in a sandbox and verify that there are no differences
w/ the content that has been checked into `docs/`

### PR DESCRIPTION
**Pull request by aledbf**
replaces #5
fixes #2

### CODE REVIEW

**Comment by aojea** [comment]
fails because the jobs needs docker  :/

> make[1]: Entering directory '/home/prow/go/src/sigs.k8s.io/service-apis'
> docker build -t k8s.gcr.io/service-apis-mkdocs:latest -f mkdocs.dockerfile .
> make[1]: docker: Command not found

**Comment by bowei** [comment]
Approved the prow setup -- let's see if it works

**Comment by aojea** [comment]
didn't merge yet 😅 , I've realized that we need a pod image with docker inside
https://github.com/kubernetes/test-infra/pull/15719

**Comment by aledbf** [comment]
It seems the prow job still uses the golang image https://prow.k8s.io/prowjob?prowjob=925e241b-2e5e-11ea-821b-5ef7b2587806

**Comment by aojea** [comment]
/test pull-service-apis-build

The PR in test-infra merged, don't know if it takes time to update prow or if I did something wrong 🤷‍♂

**Comment by aledbf** [comment]
@aojea there is some issue reloading the prow job https://kubernetes.slack.com/archives/C7J9RP96G/p1578080421043700?thread_ts=1578076927.026700&cid=C7J9RP96G

**Comment by aledbf** [comment]
@bowei the new job is working and the PR is passing now.

**Pull request merged**
