### PR TITLE
Rename `PathType` to `PathMatchType`.

### LINKED ISSUE #243: Rename `PathType` field to `PathMatchType` for consistency.
The `HTTPRouteMatch` struct has a`PathType` field for describing how to match the path, but a `headerMatchType` field to describe how to match the headers. We should align this terminology.

### PR DESCRIPTION
**Pull request by jpeach**
Since the match type for HTTP headers is named `HeaderMatchType`, rename
the patch match type to follow the same pattern.

This fixes #243.

Signed-off-by: James Peach <jpeach@vmware.com>

### CODE REVIEW

**Comment by jpeach** [comment]
@hbagdi Assuming there's consensus on this, I can rebase after #242 lands.

Note that this omits the awkwardly redundant`Type` from the constant name. If we prefer this style, I can make the same change for other types.

**Comment by robscott** [comment]
Thanks!
/lgtm

**Pull request merged**
