### PR TITLE
Reduce size of k8s.gcr.io/service-apis-mkdocs docker image

### PR DESCRIPTION
**Pull request by aledbf**
This change reduces the size of the mkdocs image from 574 to 84MB

### CODE REVIEW

**Comment by youngnick** [comment]
Not making multiple layers? Nice.

/lgtm

**Comment by bowei** [comment]
Looks like there are conflicts...

**Comment by danehans** [comment]
@aledbf when you have a moment, do you mind fixing the merge conflicts so we can get this PR merged?

**Pull request merged**
