### PR TITLE
Release cadence for Services/Ingress API

### PR DESCRIPTION
**Pull request by richarddli**
Per the discussion last week, I've drafted some details on a release cadence. I thought putting a stake in the sand of a January 31 initial release would be beneficial for everyone.

### CODE REVIEW

**Comment by rikatz** [comment]
@richarddli if this isn't a WIP anymore I suggest removing [WIP] from the title so tide can merge it :D

**Comment by richarddli** [comment]
@rikatz OK, thanks! Done.

**Pull request merged**
