### PR TITLE
de-duplicate types by embedding RouteForwardTo into HTTPRouteForwardTo

### LINKED ISSUE #440: Reuse as much as possible between HTTPRouteForwardTo and RouteForwardTo
There's a lot of overlap in these two types, and so far they've both been entirely duplicated. I believe the only difference is that `HTTPRouteForwardTo` includes filters.

### PR DESCRIPTION
**Pull request by hbagdi**
This is a breaking change for the Go API.

Fix #440

### CODE REVIEW

**Comment by robscott** [comment]
I think we should try to figure out what to do with breaking changes. Although less significant than breaking changes to the k8s APIs, I think a breaking change to the Go API is still important to get right. Maybe this is something that we need to move into v1alpha2?
/hold

**Comment by hbagdi** [comment]
> Maybe this is something that we need to move into v1alpha2?

I had assumed that this would be v1alpha2 and I had also assumed that all v1alpha2 work will be done in the `master` branch, since that's our development branch. The problem here is that our wesbite is also driven off master. This probably needs to hold until #447 is completed.

**Comment by thockin** [comment]
I'm OK with de-duplicating as long as the WHOLE type is applicable in
every context.

Any time we re-use a struct and add a comment like "field X only
apples when this type is used under a Foo" or "field Y must be 0 when
used in a Bar", I die a little inside.

**Comment by hbagdi** [comment]
> Any time we re-use a struct and add a comment like "field X only
apples when this type is used under a Foo" or "field Y must be 0 when
used in a Bar", I die a little inside.

100% agree with this.
The only field I can think of that could end up in such a situation here is `Weight`. I'd love to know what others think about it.

**Comment by hbagdi** [comment]
As discussed in community meeting on Feb 3rd, this is no longer blocked because upstream k8s allows for breaking changes in the Go API (minimize as much as possible).
I think this is a reasonable refactor but I'm open to hearing concerns around not merging this.

I can update the PR if we want to move this forward.

/hold cancel

**Comment by hbagdi** [comment]
We discussed this PR in office hours today and decided not to merge it in.
There is nothing against this PR but there are no stronger drivers for it either.
HTTPRoute is a little special than other ones and having a little duplication here doesn't harm much.

If you are reading this and feel strongly about this, please feel free to re-open.

/close

**Pull request closed without merging**
