### PR TITLE
add status subresource to UDPRoute

### PR DESCRIPTION
**Pull request by hbagdi**

### CODE REVIEW

**Comment by robscott** [comment]
Thanks!

/lgtm
/approve

**Comment by jpeach** [comment]
This is #270 right?

**Comment by jpeach** [comment]
/lgtm

👍 👍

**Comment by hbagdi** [comment]
> This is #270 right?

Yes. UDPRoute was merged after so has a bunch of holes. More PRs coming in to resolve such discrepancies.

**Comment by jpeach** [comment]
> On 11 Sep 2020, at 2:18 pm, Harry <notifications@github.com> wrote:
> 
> 
> This is #270 right?
> 
> Yes. UDPRoute was merged after so has a bunch of holes. More PRs coming in to resolve such discrepancies.

Nice! :)

**Pull request merged**
