### PR TITLE
httproute: rename Action to Forward

### PR DESCRIPTION
**Pull request by hbagdi**
/cc @jpeach @robscott

### CODE REVIEW

**Comment by hbagdi** [comment]
Once this PR merges, I'll make the same change to other Route types as well.

**Comment by robscott** [comment]
Thanks!

/lgtm
/approve

I think it's fine to combine the changes to all the other routes into a single follow up PR for simplicity.

**Comment by robscott** [comment]
To clarify the quick approval here, I think this matches discussions we've had on previous calls. If that's not the case, let me know.

**Pull request merged**
