### PR TITLE
build: Run go test from Make

### PR DESCRIPTION
**Pull request by cmluciano**
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adds Makefile task for `go test`

**Which issue(s) this PR fixes**:
xref: #507 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @cmluciano! It doesn't look like we have any go tests yet - is this in preparation for landing #506?

**Comment by cmluciano** [comment]
> Thanks @cmluciano! It doesn't look like we have any go tests yet - is this in preparation for landing #506?

Yes this is for preparation and testing of the webhook PR.

**Comment by hbagdi** [comment]
It is hard to verify if the tests are actually running in the CI since we don't have any.
I don't mind merging this in and iterating as needed.
/lgtm

**Comment by robscott** [comment]
Thanks!

/approve

**Comment by cmluciano** [comment]
Does the bot automatically merge things?

**Comment by hbagdi** [comment]
@cmluciano It usually does but something went off this time.

**Comment by cmluciano** [comment]
oh ok thx!

**Pull request merged**
