### PR TITLE
Remove the vendor directory

### PR DESCRIPTION
**Pull request by howardjohn**
This has 2 commits, one removes the folder and the other fixes two places that reference them

### CODE REVIEW

**Comment by howardjohn** [comment]
Hmm we are actually using this for the protos. Not sure if there is a better way to handle those

**Comment by bowei** [comment]
How does the vendor only protos work when it needs to be updated?

**Comment by howardjohn** [comment]
> How does the vendor only protos work when it needs to be updated?

Good question. If we did have to update them, I think it would be a manual action. However, in practice I don't think we will ever need to. Its a bit messy, but my understanding is the pb.go files will use the dep from go.mod, so on that end we are good. In the .proto file, we only depend on TypeMeta, ObjectMeta, ListMeta, and LabelSelector. I assume these will not change. If they did, I am still not sure it would cause issues because the pb.go file will still be updated. I think we will only have issues if those types change *and* service-apis itself needs to use the new fields

**Comment by bowei** [comment]
Can you drop a README with what you wrote above that in the third_party directory?

third_party/README

**Comment by aojea** [comment]
heh, impressive

+9 −1,076,929

**Comment by bowei** [comment]
John is winning the `sloccount(1)` ;-) 

[1](https://linux.die.net/man/1/sloccount)

**Comment by aojea** [comment]
lol

**Pull request merged**
