### PR TITLE
Regen docs

### PR DESCRIPTION
**Pull request by howardjohn**
I have no clue if this is right, I just ran the docs gen locally with no
changes, seems like the image changed maybe

### CODE REVIEW

**Comment by youngnick** [comment]
I think only Bowei can do this but, let's try:
/ok-to-test

**Comment by bowei** [comment]
Did you pin the `pip` or mkdocs builder? We need to do that otherwise the non-repeatable behavior will continue...

**Comment by howardjohn** [comment]
closing since @bowei fixed this. Thanks

**Pull request closed without merging**
