### PR TITLE
Generates missing protos

### PR DESCRIPTION
**Pull request by danehans**
Generates missing protos from PR #126.

/assign @robscott 
/cc @bowei

### CODE REVIEW

**Comment by robscott** [comment]
Thanks for catching this! We should really add some kind of test to verify this on PRs.

/lgtm

**Comment by danehans** [comment]
> Thanks for catching this! We should really add some kind of test to verify this on PRs.

@robscott the `pull-service-apis-build` needs to run `make verify`. What is the process for managing the CI jobs?

**Comment by danehans** [comment]
@robscott `make verify` runs the proto verification, so I'm not sure how it got through. @bowei any ideas?

**Comment by robscott** [comment]
@danehans If I'm understanding the Makefile correctly ,`make all` just runs `make controller` and `make docs` and does not seem to include `make verify`. That could probably change, and I could probably updated my test-infra PR to run `make controller` and `make verify` as the two different steps instead.

**Pull request merged**
