### PR TITLE
drop ClusterRole RBAC resource

### PR DESCRIPTION
**Pull request by hbagdi**
ClusterRole definition is not maintained.
Also updated kustomization.yaml to include UDPRoute.

### CODE REVIEW

**Comment by robscott** [comment]
Thanks!

/lgtm
/approve

**Review by howardjohn — APPROVED** [review]

**Comment by hbagdi** [comment]
TLSRoute PR got merged in. Rebased to resolve conflict.
@robscott This needs another lgtm.

**Review by howardjohn — COMMENTED** [review]
/lgtm

**Comment by robscott** [comment]
@howardjohn that's weird, maybe you need to be in kubernetes-sigs org, I can help get that set up.

/lgtm

**Pull request merged**
