### PR TITLE
Generate API documentation for the website.

### PR DESCRIPTION
**Pull request by jpeach**
Add tooling to generate online API documentation from the CRD
types. This included in the `make manifests` build target.

Signed-off-by: James Peach <jpeach@vmware.com>

### CODE REVIEW

**Comment by jpeach** [comment]
A couple of issues
- there's no verify check yet
- API string constants (e.g. condition types) don't get emitted
- the comment formatting need some HTML tags to lay out nicely

**Comment by jpeach** [comment]
> * the comment formatting need some HTML tags to lay out nicely

The tool is supposed to to markdown processing on the comments; it doesn't look to me like that is working well (e.g. paragraphs aren't there), so probably best to investigate that before sprinkling tags everywhere.

**Comment by jpeach** [comment]
@bowei LMK if you are on board for generating API docs; if so I'll tidy this PR up. Happy to add to meeting agenda if we want to have a quick discussion in the WG.

**Comment by robscott** [comment]
@jpeach This is very cool, thanks for the initial work on this! I think this would be a great addition to our docs. Likely worth discussing a bit more at office hours today.

**Comment by jpeach** [comment]
@robscott I added the verify script, so this is ready now. We can fix up any formatting documentation formatting issues in followup PRs.

**Comment by jpeach** [comment]
CI failure is verify-docs, which is #188

**Comment by jpeach** [comment]
@robscott @bowei Fixed tests, ready to go!

**Comment by robscott** [comment]
This is awesome, thanks for the work on this! This all LGTM, I just think it needs to actually be linked from the docs. I think [adding a link in the sidebar](https://github.com/kubernetes-sigs/service-apis/blob/master/docs-src/index.md) as well as one on the [main docs page](https://github.com/kubernetes-sigs/service-apis/blob/master/docs-src/index.md) replacing the current API Specification link.

**Comment by jpeach** [comment]
> This is awesome, thanks for the work on this! This all LGTM, I just think it needs to actually be linked from the docs. I think [adding a link in the sidebar](https://github.com/kubernetes-sigs/service-apis/blob/master/docs-src/index.md) as well as one on the [main docs page](https://github.com/kubernetes-sigs/service-apis/blob/master/docs-src/index.md) replacing the current API Specification link.

I did a `make serve` and AFAICT both of those links work correctly. This generates HTML directly into `docs-src/spec.md` (which is legal Markdown), so another needed to be adjusted. If I haven't interpreted your comment correctly, I'm happy to get on a call and figure it out :)

**Comment by bowei** [comment]
I'm assuming rob's LGTM is 

/lgtm
/approve

**Pull request merged**
