### PR TITLE
simplify docs generation & serve

### PR DESCRIPTION
**Pull request by M00nF1sh**
Changes:
1. remove the `docs` folder. (it will be hosted in `gh-pages` branch)
2. rename `docs-source` folder to be `docs` 👀
3. upgrade mkdocs version & enable strict check
3. usage:
    * `make docs-serve`: live-preview docs (renamed `serve` to be `docs-serve` 👀 )
    * `GITHUB_USER=<> GITHUB_TOKEN=<>make docs-deploy`:  deploy docs to `gh-pages` branch

Sample page: https://m00nf1sh.github.io/service-apis/
Sample branch: https://github.com/M00nF1sh/service-apis/tree/gh-pages

TODO:
* If we can mount a GITHUB_TOKEN to prow, we can deploy docs automatically use post-submit jobs 😃 

fix https://github.com/kubernetes-sigs/service-apis/issues/34

### CODE REVIEW

**Comment by bowei** [comment]
thanks -- can you split the commit into two, one for the new build system, and all of the deleted files etc in the other (easier to review)

**Comment by M00nF1sh** [comment]
@bowei 
Thanks :D have split the commands.
BTW, I moved the docker file back, but should we just depends on https://github.com/pypa/pipenv on local system instead of using docker?

**Comment by bowei** [comment]
My prior experience with having pip update stuff on the local system has been pretty hard to deal with, even with the python virtualization stuff (pyenv), so I would prefer the build to be completely hermetic via docker...after all it's what it was invented for :-)

**Comment by M00nF1sh** [comment]
cool :D then the current one should be good, it's based on docker 🤣

**Comment by robscott** [comment]
Hey @M00nF1sh, thanks for your initial work on this! Sorry we missed following up earlier. It looks like a lot has changed in the past few months so a rebase may end up being relatively complex. Since this PR has gone stale I'm going to close this for now, but still very open to this kind of approach. If you're still interested in this, don't hesitate to reopen the PR.

/close

**Pull request closed without merging**
