### PR TITLE
Fixing verify-golint by using mod=readonly go flag

### PR DESCRIPTION
**Pull request by robscott**
This change has been verified to work in https://github.com/kubernetes-sigs/service-apis/pull/416. 

/cc @jpeach @hbagdi

### CODE REVIEW

**Comment by jpeach** [comment]
Is there an explanation of what this fixes? Best to include that in the commit message .

**Comment by robscott** [comment]
@jpeach Good call, I've updated the commit message to be more descriptive and the PR title to match. I'm still not quite sure I 100% understand why the tests were still failing after the initial fix. Obviously this passed for the CI run on the previous PR, but any PR that modified go files seemed to fail even after the update. My theory is that the changes to go.mod and go.sum resulted in something else failing, this ensures those files won't be changed. This time I've also tested this fix on #416 to ensure the change also fixes PRs that change go files.

**Pull request merged**
