### PR TITLE
Adding a way to verify examples with kind, fixing BackendPolicy example

### PR DESCRIPTION
**Pull request by robscott**
Fixes https://github.com/kubernetes-sigs/service-apis/issues/346.

/cc @hbagdi @jpeach

### CODE REVIEW

**Comment by robscott** [comment]
I believe tests will continue to fail on this PR until https://github.com/kubernetes/test-infra/pull/19722 gets merged in.

**Comment by robscott** [comment]
@jpeach @hbagdi The test-infra PR that was blocking this has been merged in, tests are passing now. Would love to get this in ASAP to prevent any further breaking changes to examples.

**Comment by hbagdi** [comment]
Sweet. Thanks Rob!
Question: What value does `hack/verify-examples.sh` add if we are adding a check using kind itself? Should that be removed?
cc @jpeach

**Comment by robscott** [comment]
@hbagdi That's a great question - I think we can probably remove it but I'd rather save that for a follow up PR.

**Review by hbagdi — APPROVED** [review]
LGTM.
Deferring approval to @jpeach or @danehans.

**Comment by robscott** [comment]
@danehans or @hbagdi - just fixed a couple examples that were missing a port that was now required. Please take another look and LGTM when you have a chance.

**Pull request merged**
