### PR TITLE
Refactors TCPRoute API Type

### LINKED ISSUE #96: All things byte stream routing
/kind user-story

Following are features around byte streams:
- [ ] **TCP routing**: Route all traffic on a specific LoadBalancer port or NodePort to be routed to a Service in k8s. The byte stream is passed on to the usptream service as is.
- [ ] **TLS SNI-based routing with TLS termination**: Route traffic based on the SNI in TLS client hello. The TLS session is terminated by the proxy and traffic is sent upstream. It should be possible to forward the byte stream as is or send it over a new TLS session between the proxy and upstream service. See #94
- [ ] **TLS SNI-based routing (no TLS termination)** : Route traffic based on the SNI in TLS client hello but TLS termination is not performed by the proxy. The traffic is sent to the upstream service as is. Same as #123.

The above features are for TCP only. UDP support is not part of this user-story/feature.

### PR DESCRIPTION
**Pull request by danehans**
Currently, `TCPRoute` is scaffolding. This PR provides the initial `TCPRoute` API type specification. With this PR, `tcproute.spec.hostnames` is a list of hostnames used to perform SNI routing to backend objects based on `tcproute.spec.rules[].action.forwardTo`.

Partially fixes #96 

/assign @bowei 
/cc @robscott @jpeach @youngnick @Miciah @hbagdi

### CODE REVIEW

**Comment by robscott** [comment]
I know @akutz and @jeremyot were also working on something around this, some [comments on a related issue](https://github.com/kubernetes-sigs/service-apis/issues/174#issuecomment-625055193) outline what they'd been thinking. It looks like there's some overlap here, interested in what they think.

/cc @akutz @jeremyot

**Comment by akutz** [comment]
Hi @danehans,

I encourage you to collaborate on [this Google doc](https://docs.google.com/document/d/1iYJoCGYqBJPEu7nUI0bbaHFYdKsZEWm1ulfTApP0EPE/edit?usp=sharing) where @jeremyot and I are discussing the best approach to Service APIs and L4. We are not quite sure yet it is a `TCPRoute`, and that is why a previous PR (#132) to implement one was closed. We plan on socializing the conversation in one of next week's office hours.

**Comment by danehans** [comment]
@akutz thanks for making me aware of the proposal. I have provided feedback in the gdoc.

**Comment by hbagdi** [comment]
Do we still need this one?

**Comment by robscott** [comment]
I'm going to go ahead and close this now that https://github.com/kubernetes-sigs/service-apis/pull/236 is in. Feel free to reopen this if we should revisit anything on this PR.

/close

**Pull request closed without merging**
